<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{cd1d376f-9eac-485c-84d7-1fbf9a64bde5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	I0_0 : BOOL;
    Q0_0 : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>